### ISSUE TITLE
(DAE x Custom Skills) Making some "passive effects" that increase some values not work correctly

### ISSUE THREAD

**Issue by caprichozow** [misthero/dnd5e-custom-skills#13]
Foundry Version: 9.280
Module list:
![image](https://user-images.githubusercontent.com/109267376/188362701-13fd2976-8c64-4a78-b8c5-c483c13d741f.png)
Custom Skills Version: 1.0.8 _probably_ (It does show as 1.0.8 on Foundry so most likely)
DAE Version: 0.10.30

I will start it saying that I don't know the full extent of this problem, I do know however that it's affecting HP increasing effects and movement increasing effects.

**Please do ignore the absurd values**

![image](https://user-images.githubusercontent.com/109267376/188363085-7b7a1cea-dc0c-41c8-b281-a8991f523394.png)
![image](https://user-images.githubusercontent.com/109267376/188363134-b2532c80-d664-4085-8512-339fd8721cb1.png)

This is respectively the HP and Movement of this creature if I have both DAE and Custom Skills enabled, but the thing is it was supposed to be higher, it has effects that boost both it's HP and it's movement speed, which start working the second I turn Custom Skills off.

The module list that I ran this next test on

![image](https://user-images.githubusercontent.com/109267376/188363446-8f9e69e2-0273-4c7b-8ddd-2b91064b190e.png)

New HP and Movement with the working effects

![image](https://user-images.githubusercontent.com/109267376/188363558-33037891-a749-482d-b0a2-b51ad6a9ab3d.png)
![image](https://user-images.githubusercontent.com/109267376/188363575-9dbd42e5-70a2-41ae-bb60-f4622ac04f63.png)

The effects remained untouched between tests, so I don't think they're relevant at all, but they're as follows:

![image](https://user-images.githubusercontent.com/109267376/188363814-98044d43-92fd-44f4-8e4c-c4ef90ae0671.png)
![image](https://user-images.githubusercontent.com/109267376/188363861-0ff00c62-5719-4ceb-9fe9-c1a0c8e348cb.png)

I think that's about all the relevant information and even some extra, but if you do need any extra info I'll be more than happy with providing it!

Edit: **AC IS PARTIALLY WORKING, if you use "data.attributes.ac.bonus" it works fine, but not if you use data.attributes.value for some reason, which works usually, and now it's working without Custom SKills and DAE on**

**Comment by caprichozow** [comment]
Oh yeah, the reason I said probably about the version is because I wasn't able to install it through just dragging folder in the zip nor by getting it through foundry (which had a broken link and it was already reported by someone else), or even using the correct manifest link which I think it's "https://raw.githubusercontent.com/misthero/dnd5e-custom-skills/v1.0.8/module.json", I instead did what I descbribed in the broken link issue post: "https://github.com/misthero/dnd5e-custom-skills/issues/12#issuecomment-1236535067"

**Comment by misthero** [comment]
Sorry, my mistake. It should be fixed (the version issue) try removing the module and redownloading from foundry.

**Comment by caprichozow** [comment]
> Sorry, my mistake. It should be fixed (the version issue) try removing the module and redownloading from foundry.

Yup, the version one is working correctly now!

**Comment by caprichozow** [comment]
But it is as I feared, I was really on version 1.0.8 and the effects problem are really happening on it indeed

**Comment by caprichozow** [comment]
I have some more news, I just tested this again but this time with an older version of DAE and it does run without the issues I mentioned

I have ran some other tests with a older version of Custom Skills (1.0.6), which used to work with no problems, and I was still having problems.
I then reverted DAE to 0.10.29 which didn't change anything really, and then I tested it with DAE 0.9.12 and it ran with absolutely no problem like I said in the start.

So it was probably a change they made in their code, so I don't know if you can still do anything in your side to work around their code or if I should go to them instead, I'll wait for your feedback and proceed with further actions as you deem fit! Thank you either way!

**Comment by misthero** [comment]
mmm, Tim (the main dae developer) was trying to add some compatibility with this module in v 0.10+, maybe that caused some unwanted side effect.

This module isn't doing anyting on that end, once skills are created it is almost idle, not doing any calculation or anything like that

**Comment by misthero** [comment]
I'm closing since this looks non needed anymore
